name: Jazz Drive PyTubeFix

on:
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          # 🔥 YE NAYI LIBRARY HAI JO YOUTUBE KO FIX KAREGI
          pip install pytubefix playwright pyTelegramBotAPI
          playwright install chromium

      - name: Run Bot
        run: python upload.py

      - name: Save Session
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add state.json
          git commit -m "Save Login" || exit 0
          git push
