name: Jazz Drive 24/7 Multi-Bot

on:
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install playwright pyTelegramBotAPI yt-dlp
          playwright install chromium

      - name: Run Bot
        run: python upload.py

      # 🔥 SESSION KO REPO MEIN SAVE KARNA
      - name: Auto-Save Session
        if: always()
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add state.json
          git commit -m "Updated Login Session" || exit 0
          git push
          
